//ahora en next 13 react quiere usar codigo de react del lado del servidor. 
//en el componente que voy a utilizar debbo aclarar que es cliente
"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { TaskProvider } from '../context/TasksContext'
import { Navbar } from '@/components/Navbar'
import { Toaster } from './Toaster'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//contiene a todas las paginas
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TaskProvider>
          <Navbar />
          <Toaster />
          {children}
        </TaskProvider>
      </body>
    </html>
  )
}
